#!/usr/bin/env python3

import argparse
from pathlib import Path
import json
import sys

from common import phase_read_config
from local import build_local_depl
from remote import build_remote_depl
from test import build_test_depl
from generate_password_hashes import generate_password_hashes
from proxy import manage_proxy


################
# Entry points #
################

def build(
        depl_type,
        config_path,
        create_env_dirs = True,
        check_vol_source_paths_exist = True,
        register_passwords = True,
        install_symlinks_in_local_bin = True,
        force_build_docker_images = False
    ):
    '''
    Build a deployment target based on a given config file.
    Output is written to the directory specified by the `targetDir` setting.
    The flags can be used to make additional checks and to integrate the target
    with the environment. 
    
    Args:
        depl_type: Type of deployment: "local", "remote", or "test".
        config_path: Path to the Dhall config file. Must be of type
            `LocalDepl`, `RemoteDepl`, or `TestDepl` (see also `types.dhall`).
    '''

    if depl_type not in {"local", "remote", "test"}:
        raise ValueError("Invalid depl: choose from local, remote, test")

    config_path = Path(config_path).absolute()

    if depl_type == "local":
        build_local_depl(config_path, create_env_dirs, check_vol_source_paths_exist, register_passwords, install_symlinks_in_local_bin, force_build_docker_images)
    elif depl_type == "remote":
        build_remote_depl(config_path, create_env_dirs, check_vol_source_paths_exist, register_passwords, install_symlinks_in_local_bin, force_build_docker_images)
    else:
        build_test_depl(config_path, check_vol_source_paths_exist)


def view_as_json(
        depl_type,
        config_path
    ):
    '''
    Output the deployment config as a tagged JSON, written to StdOut.

    Args:
        depl_type: Type of deployment: "local", "remote", or "test".
        config_path: Path to the Dhall config file. Must be of type
            `LocalDepl`, `RemoteDepl`, or `TestDepl` (see also `types.dhall`).
    '''

    if depl_type not in {"local", "remote", "test"}:
        raise ValueError("Invalid depl: choose from local, remote, test")

    config_path = Path(config_path).absolute()

    if depl_type == "local":
        config = phase_read_config(config_path, 'tagLocalDepl')
        print(json.dumps(config, indent=2))
    elif depl_type == "remote":
        config = phase_read_config(config_path, 'tagRemoteDepl')
        print(json.dumps(config, indent=2))
    else:
        config = phase_read_config(config_path, 'tagTestDepl')
        print(json.dumps(config, indent=2))



########
# Main #
########

def parse_bool(value):
    if isinstance(value, bool):
        return value

    normalized = value.lower()
    if normalized in {'true', 'yes', '1'}:
        return True
    if normalized in {'false', 'no', '0'}:
        return False

    raise argparse.ArgumentTypeError(f'Expected a boolean value, got: {value}')


def add_bool_argument(parser, name, default, short_option=None):
    option = '--' + name.replace('_', '-')
    options = [option, '--' + name]
    if short_option is not None:
        options.insert(0, short_option)

    parser.add_argument(
        *options,
        dest=name,
        nargs='?',
        const=True,
        default=default,
        type=parse_bool)
    parser.add_argument('--no-' + name.replace('_', '-'), dest=name, action='store_false')


def make_argument_parser():
    parser = argparse.ArgumentParser(prog='depl')
    commands = parser.add_subparsers(dest='command', required=True)

    build_parser = commands.add_parser(
        'build',
        help='Build a deployment target.',
        description='Build a deployment target based on a given config file.')
    build_parser.add_argument('depl_type', choices=('local', 'remote', 'test'))
    build_parser.add_argument('config_path')
    add_bool_argument(build_parser, 'create_env_dirs', True)
    add_bool_argument(build_parser, 'check_vol_source_paths_exist', True)
    add_bool_argument(build_parser, 'register_passwords', True, '-r')
    add_bool_argument(build_parser, 'install_symlinks_in_local_bin', True, '-i')
    add_bool_argument(build_parser, 'force_build_docker_images', False, '-f')

    view_parser = commands.add_parser(
        'view-as-json',
        help='Output a deployment config as tagged JSON.')
    view_parser.add_argument('depl_type', choices=('local', 'remote', 'test'))
    view_parser.add_argument('config_path')

    password_parser = commands.add_parser(
        'generate-password-hashes',
        help='Generate a Dhall password list containing password hashes.')
    password_parser.add_argument('password_list_path')
    password_parser.add_argument('out_path')

    proxy_parser = commands.add_parser(
        'proxy',
        help='Manage the shared local-development reverse proxy.')
    proxy_parser.add_argument('action', choices=('up', 'status', 'down'))
    proxy_parser.add_argument('--quiet', action='store_true')

    return parser


def main():
    args = vars(make_argument_parser().parse_args())
    command = args.pop('command')

    if command == 'build':
        build(**args)
    elif command == 'view-as-json':
        view_as_json(**args)
    else:
        if command == 'generate-password-hashes':
            generate_password_hashes(**args)
        else:
            return manage_proxy(**args)

    return 0


if __name__ == '__main__':
    sys.exit(main())
