from pathlib import Path
import shlex
import stat
import textwrap

from common import get_template_css_dir, phase_build_bin_scripts, phase_build_dhall_artifacts, phase_build_dirs, phase_build_docker_images, phase_build_htaccess, phase_build_users_json, phase_check_volume_source_paths_exist, phase_generate_password_hashes, phase_install_symlinks_in_local_bin_function, phase_read_config, script_dir, dhall_package_path


##############
# Entrypoint #
##############

def build_local_depl(
        config_path,
        create_env_dirs,
        check_vol_source_paths_exist,
        _register_passwords,
        install_symlinks_in_local_bin,
        force_build_docker_images
    ):

    ####################
    # Read config file #
    ####################

    config = phase_read_config(config_path, 'tagLocalDepl')


    #########
    # Paths #
    #########

    conjin_dir = Path(config['depl']['conjinDir']).absolute()
    app_dir    = Path(config['depl']['appDir']).absolute()
    target_dir = Path(config['depl']['targetDir']).absolute()

    css_vol_dir          = Path(config['depl']['cssVolDir']).absolute()
    linkchecker_vol_dir  = Path(config['linkcheckerVolDir']).absolute()
    preprocess_vol_dir   = Path(config['preprocessVolDir']).absolute()
    
    errorlog_vol_dir     = Path(config['errors']['logToVolDir']).absolute()     if 'logToVolDir' in config['errors'] else None
    db_storage_vol_dir   = Path(config['db']['storageVolDir']).absolute()       if 'db' in config and 'storageVolDir' in config['db'] else None
    store_vol_dir        = Path(config['store']['volDir']).absolute()           if 'store' in config else None
    
    store_init_files_dir = Path(config['store']['initFilesDir']).absolute()     if 'store' in config and 'initFilesDir' in config['store'] else None
    store_backup_dir     = Path(config['store']['backupDir']).absolute()        if 'store' in config and 'backupDir' in config['store'] else None   

    db_init_dir          = Path(config['db']['initFilesDir']).absolute()        if 'db' in config and 'initFilesDir' in config['db'] else None
    db_backup_dir        = Path(config['db']['backupFilesVolDir']).absolute()   if 'db' in config and 'backupFilesVolDir' in config['db'] else None


    ######################################
    # Create dir structure of target dir #
    ######################################

    target_dirs_to_build = [
        target_dir,
        target_dir / 'bin',
        target_dir / 'htdocs',
    ]

    phase_build_dirs('target', target_dirs_to_build)


    ###################################################
    # Create dir structure of environment (vols etc.) #
    ###################################################

    if create_env_dirs:
        env_dirs_to_build = [
            css_vol_dir,
            linkchecker_vol_dir,
            preprocess_vol_dir,
        ]

        for module_id,module in config['depl']['modules'].items():
            if module['compileScss']:
                env_dirs_to_build.append(css_vol_dir / get_template_css_dir(config['depl']['moduleLocations'][module_id]))

        if errorlog_vol_dir is not None:
            env_dirs_to_build.append(errorlog_vol_dir)

        if db_init_dir is not None:
            env_dirs_to_build.append(db_init_dir)
        if db_storage_vol_dir is not None:
            env_dirs_to_build.append(db_storage_vol_dir)
        if db_backup_dir is not None:
            env_dirs_to_build.append(db_backup_dir)

        if store_vol_dir is not None:
            env_dirs_to_build.append(store_vol_dir)
        if store_backup_dir is not None:
            env_dirs_to_build.append(store_backup_dir)

        phase_build_dirs('environment', env_dirs_to_build)

        # Make `preprocess` and `store` dirs writable for all users
        preprocess_vol_dir.chmod(preprocess_vol_dir.stat().st_mode | stat.S_IWGRP | stat.S_IWOTH)

        if errorlog_vol_dir is not None:
            errorlog_vol_dir.chmod(errorlog_vol_dir.stat().st_mode | stat.S_IWGRP | stat.S_IWOTH)
        if store_vol_dir is not None:
            store_vol_dir.chmod(store_vol_dir.stat().st_mode | stat.S_IWGRP | stat.S_IWOTH)


    #########################################
    # Build artifacts generated from Dhall #
    ########################################

    artifacts_config_files_docker = {
        'docker-compose-yml': {
            'path':  target_dir / 'docker-compose.yml',
            'format': 'yaml'
        }
    }

    artifacts_config_files = {
        # Docker compose files
        **artifacts_config_files_docker,

        # htdocs files
        'config-json': {
            'path': target_dir / 'htdocs/config.json',
            'format': 'json'
        }
    }

    phase_build_dhall_artifacts(artifacts_config_files, config_path, 'artifactsLocal.makeArtifacts')

    # Remove artifacts generated by older versions, which split the local
    # application and LinkChecker across two Compose files.
    for obsolete_compose_file in ('docker-compose-app.yml', 'docker-compose-linkchecker.yml'):
        (target_dir / obsolete_compose_file).unlink(missing_ok=True)


    ############################
    # Build `htdocs/.htaccess` #
    ############################

    # HTTPS is not supported for LocalDeploy
    # Compression is already handled by the nginx image
    phase_build_htaccess(
        target_dir,
        conjin_dir,
        '/',
        force_https=False,
        force_www_off=False,
        force_www_on=False,
        activate_compression=False,
        permanent_redirects=config['depl']['permanentRedirects']
    )


    ############################
    # Generate password hashes #
    ############################

    users_2_hashes = phase_generate_password_hashes(config['depl']['authentication']['staticUsers2passwords'])


    ######################
    # Build `users.json` #
    ######################

    phase_build_users_json(target_dir, users_2_hashes)


    ########################################
    # Check that volume source paths exist #
    ########################################

    if check_vol_source_paths_exist:
        phase_check_volume_source_paths_exist(['docker-compose-yml-volume-sources'], config_path, 'artifactsLocal.makeArtifacts')


    #######################
    # Build Docker images #
    #######################

    if force_build_docker_images:
        phase_build_docker_images(artifacts_config_files_docker, config['depl']['dockerProjName'])


    #########################
    # Build `bin/*` scripts #
    #########################

    # Define some bash commands that are used in multiple scripts
    compose_command = textwrap.indent(textwrap.dedent(f'''\
        compose=(docker compose \\
                --file {artifacts_config_files['docker-compose-yml']['path']} \\
                --project-name {config['depl']['dockerProjName']})
        ''').strip(), '                ')
    proxy_status_command = shlex.quote(str(conjin_dir / 'deployment' / 'depl')) + ' proxy status --quiet'

    autostart_services = ['webserver']
    if 'db' in config:
        autostart_services.extend(['db', 'phpmyadmin'])

    sass_build_commands = []
    for module_id, module in config['depl']['modules'].items():
        if module['compileScss']:
            location = config['depl']['moduleLocations'][module_id]
            location_type = 'shared' if location['isShared'] else 'local'
            module_service_name = f'{location["dirName"]}-{location_type}'
            autostart_services.append(f'sass-watch-{module_service_name}')
            sass_build_commands.append(f'"${{compose[@]}}" run --rm --no-deps "sass-build-{module_service_name}"')

    indented_sass_build_commands = textwrap.indent('\n'.join(sass_build_commands), '                ')
    autostart_service_arguments = ' '.join(f'"{service}"' for service in autostart_services)

    if store_init_files_dir is None:
        store_initialization_command = ':'
    else:
        store_initialization_command = textwrap.dedent(f'''\
            "${{compose[@]}}" build webserver
            "${{compose[@]}}" run --rm --no-deps --user www-data --entrypoint sh webserver -c '
                if [ -z "$(find /files/store -mindepth 1 -print -quit)" ]; then
                    cp -R /files/store-init/. /files/store/
                fi
            '
            ''').strip()

    # Now build the scripts
    target_bin_scripts = {
        'up': {
            'path': target_dir / 'bin' / 'up',
            'content': textwrap.dedent(f'''\
                #! /bin/bash

                set -e

{compose_command}
                # Hostname routing requires the shared Conjin proxy. Fail before
                # doing any deployment work when that infrastructure is absent.
                {proxy_status_command}

                # Seed a configured store only while it is still empty.
                {store_initialization_command}

                # Sass watch mode may retain an error stylesheet when that output
                # is newer than its entry point. Compile once unconditionally so
                # startup always produces valid CSS before the watchers take over.
{indented_sass_build_commands}

                # Start the long-running services and run preprocessing only after
                # they are running and all configured health checks have passed.
                "${{compose[@]}}" up --detach --build --wait --wait-timeout 90 {autostart_service_arguments} \\
                && {target_dir / 'bin' / 'preprocess'}
                ''')
        },
        'down': {
            'path': target_dir / 'bin' / 'down',
            'content': textwrap.dedent(f'''\
                #! /bin/bash

{compose_command}
                "${{compose[@]}}" down
                ''')
        },
        'preprocess': {
            'path': target_dir / 'bin' / 'preprocess',
            'content': textwrap.dedent(f'''\
                #! /bin/bash

{compose_command}
                "${{compose[@]}}" run --rm --no-deps preprocess
                ''')
        },
        'linkchecker': {
            'path': target_dir / 'bin' / 'linkchecker',
            'content': textwrap.dedent(f'''\
                #! /bin/bash

                export LINKCHECKER_PREFIX=''

                # Iterate over all arguments passed to the script and append it
                for arg in "$@"; do
                    LINKCHECKER_PREFIX="$LINKCHECKER_PREFIX$arg/"
                done

                export USER_UID=$(id -u)
                export USER_GID=$(id -g)

{compose_command}
                "${{compose[@]}}" run --rm --no-deps --build linkchecker &&

                echo "Results are output in {config['linkcheckerVolDir']}/linkchecker-output.html, launching web browser now..."
                xdg-open "file://{config['linkcheckerVolDir']}/linkchecker-output.html"
                ''')
        }
    }

    if store_vol_dir is not None:
        target_bin_scripts['reset-store'] = {
            'path': target_dir / 'bin' / 'reset-store',
            'content': textwrap.dedent(f'''\
                #! /bin/bash

                set -euo pipefail

                if [[ "${{1:-}}" != "--yes" ]]; then
                    read -r -p "Reset the store for {config['depl']['name']}? All current store files will be deleted. [y/N] " answer
                    if [[ "$answer" != "y" && "$answer" != "Y" ]]; then
                        echo "Store reset cancelled."
                        exit 0
                    fi
                fi

{compose_command}
                # Stop the webserver so no request can modify the store while it
                # is being cleared and initialized.
                "${{compose[@]}}" stop webserver
                "${{compose[@]}}" run --rm --no-deps --user root --entrypoint sh webserver -c \\
                        'find /files/store -mindepth 1 -maxdepth 1 -exec rm -rf -- {{}} +'

                exec {target_dir / 'bin' / 'up'}
                ''')
        }

    if 'db' in config:
        reset_db_script = textwrap.dedent(f'''\
                #! /bin/bash

                set -euo pipefail

                if [[ "${{1:-}}" != "--yes" ]]; then
                    read -r -p "Reset the database for {config['depl']['name']}? All current database data will be deleted. [y/N] " answer
                    if [[ "$answer" != "y" && "$answer" != "Y" ]]; then
                        echo "Database reset cancelled."
                        exit 0
                    fi
                fi

{compose_command}
                # Stop the complete project so neither the webserver nor MariaDB
                # can access database files during the reset. --volumes removes
                # anonymous database storage when no bind directory is configured.
                "${{compose[@]}}" down --volumes --remove-orphans
                ''')

        if db_storage_vol_dir is not None:
            reset_db_script += textwrap.dedent('''\

                # Clear the bind-mounted MariaDB data directory, including hidden
                # files, through the database service so root-owned files can be
                # removed without relying on host permissions.
                "${compose[@]}" run --rm --no-deps --entrypoint sh db -c \
                        'find /var/lib/mysql -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +'
                ''')

        reset_db_script += textwrap.dedent(f'''\

                # Starting from an empty MariaDB data directory runs all configured
                # /docker-entrypoint-initdb.d files. Without any, MariaDB creates a
                # clean database server.
                exec {target_dir / 'bin' / 'up'}
                ''')

        target_bin_scripts['reset-db'] = {
            'path': target_dir / 'bin' / 'reset-db',
            'content': reset_db_script
        }
    
    if db_backup_dir is not None:
        target_bin_scripts['backup-db'] = {
            'path': target_dir / 'bin' / 'backup-db',
            'content': textwrap.dedent(f'''\
                #! /bin/bash

                # Command to pass to db container
                cmd="exec mysqldump -u root -p\"rutus\" --all-databases > /backup/snapshot-$(date '+%Y-%m-%d.%H-%M-%S').mysql.sql"

{compose_command}
                "${{compose[@]}}" exec --user "$(id -u):$(id -g)" db sh -c "${{cmd}}"
                ''')
        }
    
    if store_backup_dir is not None:
        target_bin_scripts['backup-store'] = {
            'path': target_dir / 'bin' / 'backup-store',
            'content': textwrap.dedent(f'''\
                #! /bin/bash

                # Command to pass to container
                backup_dir=snapshot-$(date '+%Y-%m-%d.%H-%M-%S')
                cmd="mkdir /files/store-backup/${{backup_dir}} && cp -r /files/store/* /files/store-backup/${{backup_dir}}/"

{compose_command}
                "${{compose[@]}}" exec --user "$(id -u):$(id -g)" webserver sh -c "${{cmd}}"
                ''')
        }

    phase_build_bin_scripts(target_bin_scripts)


    ####################
    # Install in ~/bin #
    ####################

    if install_symlinks_in_local_bin:
        phase_install_symlinks_in_local_bin_function(target_bin_scripts, config['depl']['name'])

    print('Done.')
