----------------------------------------------------
-- Locations of conjin framework, app, deployment --
----------------------------------------------------

let p = ../vendor/lucques/conjin/deployment/dhall/package.dhall
let t = p.tools
let T = p.types
let P = p.prelude

-- These files are generated by the repository setup script so this config is
-- directly evaluable by Dhall tools without embedding machine-specific paths.
let conjinDir = ./CONJIN_DIR as Text
let appDir = ./APP_DIR as Text
let deploymentsDir = ./DEPLOYMENTS_DIR as Text


let navigableTemplate = {
    , bare = T.BareModule.Shared (T.SharedBareModule.TemplateNavigable {=})
    , compileScss = True
    , config = P.JSON.null
}: T.Module

let examTemplate = {
    , bare = T.BareModule.Shared (T.SharedBareModule.TemplateExam {=})
    , compileScss = True
    , config = P.JSON.null
}: T.Module

let interbookTemplate = {
    , bare = T.BareModule.Shared (T.SharedBareModule.TemplateInterbook {=})
    , compileScss = True
    , config = P.JSON.null
}: T.Module

let bootstrapExtendedModule = {
    , bare = T.BareModule.Shared (T.SharedBareModule.BootstrapExtended {=})
    , compileScss = True
    , config = P.JSON.null
}: T.Module

let modules = [ navigableTemplate, examTemplate, interbookTemplate, bootstrapExtendedModule ]


let authorization = T.Authorization::{
    , actorsXprivileges = [
        , t.grantPreprocPrivToStaticUser "preprocess"
        , t.grantCustomPrivToStaticUser "issue-tracker-test-write" "guest"
    ]
    , actorsXtargetRules = [
        , t.allowViewActionForStaticUser (P.List.empty Text) "guest"
        , t.denyViewActionToStaticUser ["module-tests-expect-success", "nav-view"] "guest"
        , t.allowViewActionForStaticUser ["module-tests-expect-success", "nav-view", "structural"] "guest"
        , t.denyViewActionToStaticUser ["module-tests-expect-success", "nav-view", "structural", "hidden-only-parent", "hidden-child"] "guest"
        , t.allowViewActionForStaticUser ["module-tests-expect-success", "nav-view", "empty"] "guest"
        , t.denyViewActionToStaticUser ["module-tests-expect-success", "nav-view", "empty", "hidden-child"] "guest"
        , t.denyViewActionToStaticUser ["login-profile"] "guest"
    ]
}

in {
    , p
    , conjinDir
    , appDir
    , deploymentsDir
    , sharedBareModules = p.sharedModuleCollections.full
    , localBareModules = P.List.empty T.LocalBareModule
    , modules
    , authorization
}
