#!/usr/bin/env bash

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${script_dir}/../_build-lib.sh"
dependency_build_init "${script_dir}"

clear_outputs res
copy_file "${repository_dir}/node_modules/fullcalendar/index.global.min.js" "res/dist/index.global.min.js"
copy_file "${repository_dir}/node_modules/@fullcalendar/bootstrap5/index.global.min.js" "res/packages/bootstrap5/index.global.min.js"
copy_file "${repository_dir}/node_modules/@fullcalendar/daygrid/index.global.min.js" "res/packages/daygrid/index.global.min.js"
