#!/usr/bin/env python3

from pathlib import Path
import fire
import subprocess
import json
import os
import stat
import textwrap
from pprint import pprint
from packaging import version, specifiers


# Globals
script_dir = Path(os.path.dirname(os.path.realpath(__file__)))
types_path = script_dir / 'types.dhall'
tools_path = script_dir / 'tools-internal.dhall'


###################
# DockerNginxDepl #
###################

def build_docker_nginx_depl(config_path, install_symlinks_in_local_bin = False):
    '''
    Input must be a file containing a Dhall expression of type `DockerNginxDepl`
    (see also tools.dhall).
    Output is written to the directory specified by the `targetDir` setting.
    The flag `install_symlinks_in_local_bin` can be used to install symlinks to
    the generated scripts in `~/bin`.
    '''
        
    config_path = Path(config_path).absolute()

    ####################
    # Read config file #
    ####################

    config = phase_read_config(config_path, 'tagDockerNginxDepl')


    #########
    # Paths #
    #########

    conjin_dir = Path(config['depl']['conjinDir']).absolute()
    app_dir    = Path(config['depl']['appDir']).absolute()
    target_dir = Path(config['depl']['targetDir']).absolute()

    linkchecker_vol_dir = Path(config['linkcheckerVolDir']).absolute()
    preprocess_vol_dir  = Path(config['preprocessVolDir']).absolute()


    #####################################
    # Check that conjin version matches #
    #####################################

    phase_check_conjin_version(conjin_dir, app_dir)


    ##############################
    # Create directory structure #
    ##############################

    target_dirs = [
        linkchecker_vol_dir,
        preprocess_vol_dir,
        target_dir,
        target_dir / 'bin',
        target_dir / 'htdocs',
    ]

    for module in config['depl']['modules'].values():
        if module['compileScss']:
            target_dirs.append(target_dir / 'htdocs' / get_template_css_dir(module['location']))

    if 'db' in config:
        target_dirs.append(Path(config['db']['volDir']))

    phase_build_dirs(target_dirs)

    # Make `preprocess` dir writable for all users
    preprocess_vol_dir.chmod(preprocess_vol_dir.stat().st_mode | stat.S_IWGRP | stat.S_IWOTH)


    ###########################################
    # Build config files generated from Dhall #
    ###########################################

    target_config_files_docker = {
        'docker-compose-app-yml': {
            'path':   target_dir / 'docker-compose-app.yml',
            'format': 'yaml'
        },
        'docker-compose-linkchecker-yml': {
            'path':  target_dir / 'docker-compose-linkchecker.yml',
            'format': 'yaml'
        },
    }

    target_config_files = {
        **target_config_files_docker,
        'config-json': {
            'path': target_dir / 'htdocs/config.json',
            'format': 'json'
        }
    }

    phase_build_dhall_config_files(target_config_files, config_path, 'makeDockerNginxConfigFiles')


    ##################################################
    # Build `users.json` file and register passwords #
    ##################################################

    phase_build_user_json_file_and_register_passwords(
        target_dir,
        config['depl']['authentication']['users2passwords'],
        config['depl']['desktopIntegration']['preprocessScriptUser'],
        config['depl']['desktopIntegration']['preprocessScriptPasswordRegisterCmd'],
        config['linkcheckerUser'],
        config['linkcheckerPasswordRegisterCmd']
    )


    ############################
    # Build `htdocs/.htaccess` #
    ############################

    # HTTPS is not supported for DockerNginxDeploy
    # Compression is already handled by the nginx image
    phase_build_htaccess(target_dir, conjin_dir, force_https=False, activate_compression=False)
    

    #######################
    # Build Docker images #
    #######################

    phase_build_docker_images(target_config_files_docker, config['depl']['dockerProjName'])


    #########################
    # Build `bin/*` scripts #
    #########################

    target_bin_scripts = {
        'up': {
            'path': target_dir / 'bin' / 'up',
            'content': textwrap.dedent(f'''\
                #! /bin/bash

                docker compose \\
                        --file         {target_config_files['docker-compose-app-yml']['path']} \\
                        --project-name {config['depl']['dockerProjName']} \\
                        up --detach \\
                && sleep 1 \\
                && {target_dir / 'bin' / 'preprocess'} \\
                ''')
        },
        'down': {
            'path': target_dir / 'bin' / 'down',
            'content': textwrap.dedent(f'''\
                #! /bin/bash

                docker compose \\
                        --file         {target_config_files['docker-compose-app-yml']['path']} \\
                        --project-name {config['depl']['dockerProjName']} \\
                        down
                ''')
        },
        'linkchecker': {
            'path': target_dir / 'bin' / 'linkchecker',
            'content': textwrap.dedent(f'''\
                #! /bin/bash

                export LINKCHECKER_PREFIX=''

                # Iterate over all arguments passed to the script and append it
                for arg in "$@"; do
                    LINKCHECKER_PREFIX="$LINKCHECKER_PREFIX$arg/"
                done

                export UID="$(id -u)"
                export GID="$(id -g)"
                export LINKCHECKER_PASSWORD=`{config['linkcheckerPasswordLookupCmd']}` &&
                docker compose \\
                        --file         {target_config_files['docker-compose-linkchecker-yml']['path']} \\
                        --project-name {config['depl']['dockerProjName']} \\
                        up &&

                echo "Results are output in {config['linkcheckerVolDir']}/linkchecker-output.html, launching web browser now..."
                xdg-open "file://{config['linkcheckerVolDir']}/linkchecker-output.html"
                ''')
        }
    }

    target_bin_scripts['preprocess'] = make_preprocess_target_bin_script(
        target_dir,
        config['nginxVirtualHost'],
        False, # HTTPS is not supported for DockerNginxDepl
        config['depl']['desktopIntegration']['preprocessScriptUser'],
        config['depl']['desktopIntegration']['preprocessScriptPasswordLookupCmd'])

    phase_build_bin_scripts(target_bin_scripts)


    ####################
    # Install in ~/bin #
    ####################

    if install_symlinks_in_local_bin:
        phase_install_symlinks_in_local_bin_function(target_bin_scripts, config['depl']['name'])

    print('Done.')


##################
# DockerSyncDepl #
##################

def build_sync_depl(config_path, install_symlinks_in_local_bin = False):
    '''
    Input must be a file containing a Dhall expression of type `DockerSyncDepl`
    (see also tools.dhall).
    Output is written to the directory specified by the `targetDir` setting.
    The flag `install_symlinks_in_local_bin` can be used to install symlinks to
    the generated scripts in `~/bin`.
    '''
    
    config_path = Path(config_path).absolute()

    ####################
    # Read config file #
    ####################

    config = phase_read_config(config_path, 'tagDockerSyncDepl')


    #########
    # Paths #
    #########

    conjin_dir = Path(config['depl']['conjinDir']).absolute()
    app_dir    = Path(config['depl']['appDir']).absolute()
    target_dir = Path(config['depl']['targetDir']).absolute()


    #####################################
    # Check that conjin version matches #
    #####################################

    phase_check_conjin_version(conjin_dir, app_dir)


    ##############################
    # Create directory structure #
    ##############################

    target_dirs = [
        target_dir,
        target_dir / 'bin',
        target_dir / 'htdocs',
        target_dir / 'htdocs' / 'preprocess'
    ]

    for module in config['depl']['modules'].values():
        if module['compileScss']:
            target_dirs.append(target_dir / 'htdocs' / get_template_css_dir(module['location']))

    phase_build_dirs(target_dirs)


    ###########################################
    # Build config files generated from Dhall #
    ###########################################

    target_config_files_docker = {
        'docker-compose-sync-yml': {
            'path': target_dir / 'docker-compose-sync.yml',
            'format': 'yaml'
        }
    }

    target_config_files = {
        **target_config_files_docker,
        'config-json': {
            'path': target_dir / 'htdocs/config.json',
            'format': 'json'
        }
    }

    phase_build_dhall_config_files(target_config_files, config_path, 'makeDockerSyncConfigFiles')


    ##################################################
    # Build `users.json` file and register passwords #
    ##################################################

    phase_build_user_json_file_and_register_passwords(
        target_dir,
        config['depl']['authentication']['users2passwords'],
        config['depl']['desktopIntegration']['preprocessScriptUser'],
        config['depl']['desktopIntegration']['preprocessScriptPasswordRegisterCmd']
    )


    ############################
    # Build `htdocs/.htaccess` #
    ############################

    phase_build_htaccess(target_dir, conjin_dir, force_https=config['forceHTTPS'], activate_compression=config['activateCompression'])
    

    #######################
    # Build Docker images #
    #######################

    phase_build_docker_images(target_config_files_docker, config['depl']['dockerProjName'])


    #########################
    # Build `bin/*` scripts #
    #########################

    target_bin_scripts = {
        'sync': {
            'path': target_dir / 'bin' / 'sync',
            'content': textwrap.dedent(f'''\
                #! /bin/bash
                
                export UID="$(id -u)"
                export GID="$(id -g)"
                docker compose \\
                        --file         {target_config_files['docker-compose-sync-yml']['path']} \\
                        --project-name {config['depl']['dockerProjName']}-sync \\
                        up \\
                && sleep 1 \\
                && {target_dir / 'bin' / 'preprocess'} \\
            ''')
        }
    }

    target_bin_scripts['preprocess'] = make_preprocess_target_bin_script(
        target_dir,
        config['host'],
        config['preferHTTPS'],
        config['depl']['desktopIntegration']['preprocessScriptUser'],
        config['depl']['desktopIntegration']['preprocessScriptPasswordLookupCmd'])

    phase_build_bin_scripts(target_bin_scripts)


    ####################
    # Install in ~/bin #
    ####################

    if install_symlinks_in_local_bin:
        phase_install_symlinks_in_local_bin_function(target_bin_scripts, config['depl']['dockerProjName'])

    
    print('Done.')


####################
# Helper functions #
####################

def phase_read_config(config_path, function):
    print('Reading config file...')

    input = f'(({types_path}).{function} ({config_path}))'
    config_json = subprocess.check_output('dhall-to-json', input=input, shell=True, text=True)

    return json.loads(config_json)


def phase_check_conjin_version(conjin_dir, app_dir):
    print('Checking conjin version...')

    conjin_metadata_file = conjin_dir / 'metadata.json'
    app_metadata_file    = app_dir    / 'metadata.json'

    conjin_metadata = json.loads(conjin_metadata_file.read_text())
    app_metadata    = json.loads(app_metadata_file.read_text())

    conjin_version_given = version.parse(conjin_metadata['version'])
    conjin_version_spec  = specifiers.SpecifierSet(app_metadata['conjinVersion'])

    if conjin_version_given not in conjin_version_spec:
        raise Exception(f'Conjin version {conjin_version_spec} required, but only {conjin_version_given} is available.')


def phase_build_dirs(target_dirs):
    print('Building dirs...')

    for path in target_dirs:
        path.mkdir(parents=True, exist_ok=True)


def phase_build_dhall_config_files(target_config_files, config_path, tools_function):
    print('Building config files from Dhall config...')

    for key,file in target_config_files.items():
        command = 'dhall-to-' + file['format']
        input = f'(({tools_path}).{tools_function} ({config_path})).{key}'

        print('- ' + key + '...')
        content = subprocess.check_output(command, input=input, shell=True, text=True)

        file['path'].write_text(content)


def phase_build_user_json_file_and_register_passwords(target_dir, users2passwords, preprocessingUser, preprocessingCmd = None, linkcheckerUser = None, linkcheckerCmd = None):
    print('Building users.json file...')

    users_2_hashes = {}

    for user, tagged_password in users2passwords.items():
        # Register preprocess script password, if given
        if preprocessingUser == user and preprocessingCmd is not None:
            assert tagged_password['tag'] == 'Plain', 'Password for preprocess script must be in plain text.'

            print('- Registering preprocessing script password...')
            subprocess.run(preprocessingCmd, input=tagged_password['contents'], shell=True, text=True)

        # Register linkchecker password, if given
        if linkcheckerUser == user and linkcheckerCmd is not None:
            assert tagged_password['tag'] == 'Plain', 'Password for linkchecker must be in plain text.'

            print('- Registering linkchecker password...')
            subprocess.run(linkcheckerCmd, input=tagged_password['contents'], shell=True, text=True)

        # Hash password for users.json file
        if tagged_password['tag'] == 'Plain':
            password = tagged_password['contents']

            print('- Hashing password for ' + user + '...')
            hash = subprocess.check_output(f"docker run -it php:8.2-cli php -r 'print(password_hash(\"{ password }\", PASSWORD_DEFAULT));'", shell=True, text=True)
            users_2_hashes[user] = hash
        else:
            hash = tagged_password['contents']
            users_2_hashes[user] = hash
    
    users_2_hases_json = json.dumps(users_2_hashes, indent=4)
    (target_dir / 'htdocs/users.json').write_text(users_2_hases_json)


def phase_build_htaccess(target_dir, conjin_dir, force_https, activate_compression):
    print('Building .htaccess file...')

    content  = (conjin_dir / 'src/htaccess_header').read_text() + '\n\n'
    
    if force_https:
        content += (conjin_dir / 'src/htaccess_force_https').read_text() + '\n\n'

    if activate_compression:
        content += (conjin_dir / 'src/htaccess_activate_compression').read_text() + '\n\n'

    content += (conjin_dir / 'src/htaccess_footer').read_text()

    (target_dir / 'htdocs/.htaccess').write_text(content)


def phase_build_docker_images(target_config_files, docker_proj_name):
    print('Building Docker images...')

    for file in target_config_files.values():
        print(f'- {file["path"]}...')
        subprocess.run(f'docker compose --file "{file["path"]}" --project-name "{docker_proj_name}" build', shell=True)


def make_preprocess_target_bin_script(target_dir: str, host: str, prefer_https: bool, user: str, password_retrieval_cmd: str):
    return {
        'path': target_dir / 'bin' / 'preprocess',
        'content': textwrap.dedent(f'''\
            #! /bin/bash
            # This script was auto-generated.

            # Read Password and send it to the server
            password=`{password_retrieval_cmd}` &&
            curl --cookie "user={user}; password=$password" {'https' if prefer_https else 'http'}://{host}/preprocess/
            ''')
    }


def phase_build_bin_scripts(target_bin_scripts):
    print('Building bin scripts...')

    for file in target_bin_scripts.values():
        file['path'].write_text(file['content'])
        # Make file executable
        st = os.stat(file['path'])
        os.chmod(file['path'], st.st_mode | stat.S_IEXEC)


def phase_install_symlinks_in_local_bin_function(bin_scripts, depl_name):
    print('Installing symlinks in ~/bin...')

    local_bin_dir = Path.home() / 'bin'
    local_bin_dir.mkdir(parents=True, exist_ok=True)

    for file in bin_scripts.values():
        link_path = local_bin_dir / (depl_name + '-' + file['path'].name)
        if link_path.exists():
            link_path.unlink()

        os.symlink(file['path'], link_path)


def get_template_css_dir(module_location):
    if module_location['isShared'] and module_location['isExternal']:
        return 'modules-shared-ext-css/' + module_location['dirName']
    elif module_location['isShared'] and not module_location['isExternal']:
        return 'modules-shared-css/' + module_location['dirName']
    elif not module_location['isShared'] and module_location['isExternal']:
        return 'modules-ext-css/' + module_location['dirName']
    else:
        return 'modules-css/' + module_location['dirName']


########
# Main #
########

if __name__ == '__main__':
    fire.Fire({
        'build-docker-nginx-depl': build_docker_nginx_depl,
        'build-sync-depl':         build_sync_depl,
    })