#!/usr/bin/env python3

import fire
import subprocess

def generate_users(password):
    '''
    Input must be a password.
    Output is the hash.
    '''

    hash = subprocess.check_output(f"docker run -it --rm php:8.2-cli php -r 'print(password_hash(\"{ password }\", PASSWORD_DEFAULT));'", shell=True, text=True)
    print(hash)


########
# Main #
########

if __name__ == '__main__':
    fire.Fire(generate_password_hash)