----------------------------------------------------
-- Locations of conjin framework, app, deployment --
----------------------------------------------------

-- Import Conjin through Composer's installed package tree. The repository uses
-- a symlinked path package during development; published consumers get the same
-- layout as an ordinary Composer dependency.
let p = ../vendor/lucques/conjin/deployment/dhall/package.dhall
let t = p.tools
let T = p.types
let P = p.prelude

-- These local files are generated by the repository's setup script.  Keeping
-- the machine-specific absolute paths here lets this configuration remain
-- directly evaluable by Dhall tools and editor integrations.
let conjinDir      = ./CONJIN_DIR      as Text
let appDir         = ./APP_DIR         as Text
let deploymentsDir = ./DEPLOYMENTS_DIR as Text


-------------------
-- Common config --
-------------------

let navigableTemplate = {
  , bare = T.BareModule.Shared (T.SharedBareModule.TemplateNavigable {=})
  , compileScss = True
  , config = P.JSON.null
}: T.Module

let bootstrapExtendedModule = {
  , bare = T.BareModule.Shared (T.SharedBareModule.BootstrapExtended {=})
  , compileScss = True
  , config = P.JSON.null
}: T.Module

let interbookTemplate = {
  , bare = T.BareModule.Shared (T.SharedBareModule.TemplateInterbook {=})
  , compileScss = True
  , config = P.JSON.null
}: T.Module

let examTemplate = {
  , bare = T.BareModule.Shared (T.SharedBareModule.TemplateExam {=})
  , compileScss = True
  , config = P.JSON.null
}: T.Module

let modules = [ navigableTemplate, bootstrapExtendedModule, interbookTemplate, examTemplate ]

let authorization = T.Authorization::{
    , actorsXprivileges = [
        , t.grantPreprocPrivToStaticUser "preprocess"
    ]
    , actorsXtargetRules = [
        , t.allowViewActionForStaticUser (P.List.empty Text) "guest"
    ]
}

in
    {
      , p

      , conjinDir
      , appDir
      , deploymentsDir
      , sharedBareModules = p.sharedModuleCollections.full
      , localBareModules  = P.List.empty T.LocalBareModule
      , modules
      , authorization
    }
