#!/usr/bin/env bash

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${script_dir}/../_build-lib.sh"
dependency_build_init "${script_dir}"

clear_outputs res
copy_file "${repository_dir}/node_modules/tom-select/dist/js/tom-select.complete.min.js" "res/tom-select.complete.min.js"
copy_file "${repository_dir}/node_modules/tom-select/dist/css/tom-select.css" "res/tom-select.css"
