#!/usr/bin/env bash

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${script_dir}/../_build-lib.sh"
dependency_build_init "${script_dir}"

clear_outputs res
copy_file "${repository_dir}/node_modules/@picocss/pico/css/pico.min.css" "res/pico.min.css"
copy_file "${repository_dir}/node_modules/@picocss/pico/css/pico.classless.min.css" "res/pico.classless.min.css"
